# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180126_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mappa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('aggettivo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mappa', models.CharField(default='', max_length=100)),
                ('nord', models.IntegerField(blank=True, null=True)),
                ('sud', models.IntegerField(blank=True, null=True)),
                ('est', models.IntegerField(blank=True, null=True)),
                ('ovest', models.IntegerField(blank=True, null=True)),
                ('id_temporale', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Puntini',
        ),
    ]
