# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180207_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappa',
            name='aggettivo',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
