# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180207_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('nome_mappa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Punti')),
            ],
        ),
    ]
