# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_grafico'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappa',
            name='nome_mappa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Punti'),
        ),
        migrations.AlterField(
            model_name='grafico',
            name='nome_mappa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Punti'),
        ),
    ]
