# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180207_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mappa', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='grafico',
            name='nome_mappa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Nome'),
        ),
        migrations.AlterField(
            model_name='mappa',
            name='nome_mappa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Nome'),
        ),
        migrations.AlterField(
            model_name='punti',
            name='nome_mappa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Nome'),
        ),
    ]
