# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.10 on 2018-04-14 18:56
=======
# Generated by Django 1.11.7 on 2018-04-13 20:15
>>>>>>> 29d230175dcd616d9550f7db7aaf378d08c39959
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180209_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
