# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180209_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
